#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 15 19:32:20 2019

@author: vanessafung
"""

import math as mt

#algrithm of distinguishing weekdays and weekend
fot i in day:
    if day[i]%7==1 |day[i]%7==0:
        return weekend
    else:
        return weekdays

def distance(lat1,lon1,lat2,lon2):
    '''
    a function to calculate distance based on two points' latitude and longitude
    '''
    lat1,lon1,lat2,lon2 = map(mt.radians, [lat1,lon1,lat2,lon2])
    dlon=lon2-lon1
    dlat=lat2-lat1
    a=mt.sin(dlat/2)**2 + mt.cos(lat1) * mt.cos(lat2) * mt.sin(dlon/2)**2 
    distance=2*mt.asin(mt.sqrt(a))*6371*1000
    return distance
distance(55.96399515	,-3.185188768,55.97544143,-3.166806411)

trip_dis = []
for i,j,k,l in zip(lat1.list,lon1.list,lat2.list,lon2.list):
    trip_dis.append(distance(i,j,k,l))
    