#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 12 19:23:23 2019

@author: vanessafung
"""
import numpy as np
import csv

with open('/Users/vanessafung/Desktop/cyclingtrips_Sep2019.csv','r') as csvfile:
    reader = csv.DictReader(csvfile)
    duration = [row['duration'] for row in reader]
    

with open('/Users/vanessafung/Desktop/cyclingtrips_Sep2019.csv', 'r') as csvFile:
    reader = csv.reader(csvFile)
    duration_sec = [row[2] for row in reader]

import folium

for i,j,k in zip([55.9474092,55.95003729,55.93715871],[-3.205765497,-3.187821519,-3.20643533],[0.2,0.5,0.3]):
    m = folium.Map(
        location=[i, j],
        zoom_start=15
    )
    folium.CircleMarker(
        location=[i, j],
        radius=k,
        color='blue',
        fill=True,
        fill_color='blue'
    ).add_to(m)
m
